language: node_js
node_js:
  - 12
  - 10
  - 8
  - 6
before_install:
  - npm config set depth 0
before_script:
  - 'if [ "${ESLINT-}" == "6" ]; then npm install --no-save "eslint@${ESLINT}" ; fi'
  - 'if [ "${ESLINT-}" == "5" ]; then npm install --no-save "eslint@${ESLINT}" eslint-config-canonical@17.1.2 eslint-plugin-unicorn@8.0.2 ; fi'
notifications:
  email: false
sudo: false
script:
  - npm run test
  - 'if [ -n "${LINT-}" ]; then npm run lint; fi'
  - 'if [ -n "${CHECK_README-}" ]; then npm run check-readme; fi'
  - npm run build
env:
  matrix:
    - ESLINT=6
    - ESLINT=5
matrix:
  fast_finish: true
  include:
    - node_js: 'lts/*'
      env: LINT=true
    - node_js: 'lts/*'
      env: CHECK_README=true
  exclude:
    - node_js: 6
      env: ESLINT=6
after_success:
  - export NODE_ENV=production
  - npm run build
  - semantic-release
