language: node_js
node_js:
  - 12
  - 10
  - 8
before_install:
  - npm config set depth 0
before_script: >
  node_version=$(node -v);
  if [ ${node_version:3:1} = "." ]; then
    echo "Node 10+"
    npm install --no-save "eslint@${ESLINT}"
    else
      echo "Node 8+"
      npm install --no-save "eslint@${ESLINT}" husky@3.1.0 semantic-release@15.14.0
  fi
notifications:
  email: false
sudo: false
script:
  - npm run test
  - 'if [ -n "${LINT-}" ]; then npm run lint; fi'
  - npm run build
env:
  matrix:
    - ESLINT=6
matrix:
  fast_finish: true
  include:
    - node_js: 'lts/*'
      env: LINT=true
after_success:
  - export NODE_ENV=production
  - npm run build
  - semantic-release
