language: node_js
node_js:
  - 12
  - 10
  - 8
  - 6
before_install:
  - npm config set depth 0
before_script: >
  node_version=$(node -v);
  if [ ${node_version:3:1} = "." ]; then
    echo "Node 10+"
    npm install --no-save "eslint@${ESLINT}"
    else
      if [ ${node_version:1:1} -ge 8 ]; then
        echo "Node 8+"
        npm install --no-save "eslint@${ESLINT}" husky@3.1.0 semantic-release@15.14.0
      else
        echo "Node <= 6"
        npm install --no-save "eslint@${ESLINT}" husky@3.1.0 semantic-release@15.14.0 mocha@6.2.2 nyc@14.1.1 babel-plugin-istanbul@5.2.0 eslint-config-canonical@17.1.2 eslint-plugin-unicorn@8.0.2 @typescript-eslint/parser@1.13.0
      fi
  fi
notifications:
  email: false
sudo: false
script:
  - npm run test
  - 'if [ -n "${LINT-}" ]; then npm run lint; fi'
  - npm run build
env:
  matrix:
    - ESLINT=6
    - ESLINT=5
matrix:
  fast_finish: true
  include:
    - node_js: 'lts/*'
      env: LINT=true
  exclude:
    - node_js: 6
      env: ESLINT=6
after_success:
  - export NODE_ENV=production
  - npm run build
  - semantic-release
